use nerust_gui_settings::input::KeyboardKey;

const EDITABLE_KEYS: &[KeyboardKey] = &[
    KeyboardKey::KeyA,
    KeyboardKey::KeyB,
    KeyboardKey::KeyC,
    KeyboardKey::KeyD,
    KeyboardKey::KeyE,
    KeyboardKey::KeyF,
    KeyboardKey::KeyG,
    KeyboardKey::KeyH,
    KeyboardKey::KeyI,
    KeyboardKey::KeyJ,
    KeyboardKey::KeyK,
    KeyboardKey::KeyL,
    KeyboardKey::KeyM,
    KeyboardKey::KeyN,
    KeyboardKey::KeyO,
    KeyboardKey::KeyP,
    KeyboardKey::KeyQ,
    KeyboardKey::KeyR,
    KeyboardKey::KeyS,
    KeyboardKey::KeyT,
    KeyboardKey::KeyU,
    KeyboardKey::KeyV,
    KeyboardKey::KeyW,
    KeyboardKey::KeyX,
    KeyboardKey::KeyY,
    KeyboardKey::KeyZ,
    KeyboardKey::ArrowUp,
    KeyboardKey::ArrowDown,
    KeyboardKey::ArrowLeft,
    KeyboardKey::ArrowRight,
    KeyboardKey::Enter,
    KeyboardKey::Escape,
    KeyboardKey::Space,
    KeyboardKey::Tab,
    KeyboardKey::F1,
    KeyboardKey::F2,
    KeyboardKey::F3,
    KeyboardKey::F4,
    KeyboardKey::F5,
    KeyboardKey::F6,
    KeyboardKey::F7,
    KeyboardKey::F8,
    KeyboardKey::F9,
    KeyboardKey::F10,
    KeyboardKey::F11,
    KeyboardKey::F12,
];

pub fn editable_keys() -> &'static [KeyboardKey] {
    EDITABLE_KEYS
}

pub fn keyboard_key_label(key: KeyboardKey) -> &'static str {
    match key {
        KeyboardKey::KeyA => "A",
        KeyboardKey::KeyB => "B",
        KeyboardKey::KeyC => "C",
        KeyboardKey::KeyD => "D",
        KeyboardKey::KeyE => "E",
        KeyboardKey::KeyF => "F",
        KeyboardKey::KeyG => "G",
        KeyboardKey::KeyH => "H",
        KeyboardKey::KeyI => "I",
        KeyboardKey::KeyJ => "J",
        KeyboardKey::KeyK => "K",
        KeyboardKey::KeyL => "L",
        KeyboardKey::KeyM => "M",
        KeyboardKey::KeyN => "N",
        KeyboardKey::KeyO => "O",
        KeyboardKey::KeyP => "P",
        KeyboardKey::KeyQ => "Q",
        KeyboardKey::KeyR => "R",
        KeyboardKey::KeyS => "S",
        KeyboardKey::KeyT => "T",
        KeyboardKey::KeyU => "U",
        KeyboardKey::KeyV => "V",
        KeyboardKey::KeyW => "W",
        KeyboardKey::KeyX => "X",
        KeyboardKey::KeyY => "Y",
        KeyboardKey::KeyZ => "Z",
        KeyboardKey::Digit0 => "0",
        KeyboardKey::Digit1 => "1",
        KeyboardKey::Digit2 => "2",
        KeyboardKey::Digit3 => "3",
        KeyboardKey::Digit4 => "4",
        KeyboardKey::Digit5 => "5",
        KeyboardKey::Digit6 => "6",
        KeyboardKey::Digit7 => "7",
        KeyboardKey::Digit8 => "8",
        KeyboardKey::Digit9 => "9",
        KeyboardKey::ArrowUp => "Up",
        KeyboardKey::ArrowDown => "Down",
        KeyboardKey::ArrowLeft => "Left",
        KeyboardKey::ArrowRight => "Right",
        KeyboardKey::Enter => "Enter",
        KeyboardKey::Escape => "Escape",
        KeyboardKey::Space => "Space",
        KeyboardKey::Tab => "Tab",
        KeyboardKey::F1 => "F1",
        KeyboardKey::F2 => "F2",
        KeyboardKey::F3 => "F3",
        KeyboardKey::F4 => "F4",
        KeyboardKey::F5 => "F5",
        KeyboardKey::F6 => "F6",
        KeyboardKey::F7 => "F7",
        KeyboardKey::F8 => "F8",
        KeyboardKey::F9 => "F9",
        KeyboardKey::F10 => "F10",
        KeyboardKey::F11 => "F11",
        KeyboardKey::F12 => "F12",
    }
}

pub fn keyboard_key_id(key: KeyboardKey) -> &'static str {
    match key {
        KeyboardKey::KeyA => "key_a",
        KeyboardKey::KeyB => "key_b",
        KeyboardKey::KeyC => "key_c",
        KeyboardKey::KeyD => "key_d",
        KeyboardKey::KeyE => "key_e",
        KeyboardKey::KeyF => "key_f",
        KeyboardKey::KeyG => "key_g",
        KeyboardKey::KeyH => "key_h",
        KeyboardKey::KeyI => "key_i",
        KeyboardKey::KeyJ => "key_j",
        KeyboardKey::KeyK => "key_k",
        KeyboardKey::KeyL => "key_l",
        KeyboardKey::KeyM => "key_m",
        KeyboardKey::KeyN => "key_n",
        KeyboardKey::KeyO => "key_o",
        KeyboardKey::KeyP => "key_p",
        KeyboardKey::KeyQ => "key_q",
        KeyboardKey::KeyR => "key_r",
        KeyboardKey::KeyS => "key_s",
        KeyboardKey::KeyT => "key_t",
        KeyboardKey::KeyU => "key_u",
        KeyboardKey::KeyV => "key_v",
        KeyboardKey::KeyW => "key_w",
        KeyboardKey::KeyX => "key_x",
        KeyboardKey::KeyY => "key_y",
        KeyboardKey::KeyZ => "key_z",
        KeyboardKey::Digit0 => "digit_0",
        KeyboardKey::Digit1 => "digit_1",
        KeyboardKey::Digit2 => "digit_2",
        KeyboardKey::Digit3 => "digit_3",
        KeyboardKey::Digit4 => "digit_4",
        KeyboardKey::Digit5 => "digit_5",
        KeyboardKey::Digit6 => "digit_6",
        KeyboardKey::Digit7 => "digit_7",
        KeyboardKey::Digit8 => "digit_8",
        KeyboardKey::Digit9 => "digit_9",
        KeyboardKey::ArrowUp => "arrow_up",
        KeyboardKey::ArrowDown => "arrow_down",
        KeyboardKey::ArrowLeft => "arrow_left",
        KeyboardKey::ArrowRight => "arrow_right",
        KeyboardKey::Enter => "enter",
        KeyboardKey::Escape => "escape",
        KeyboardKey::Space => "space",
        KeyboardKey::Tab => "tab",
        KeyboardKey::F1 => "f1",
        KeyboardKey::F2 => "f2",
        KeyboardKey::F3 => "f3",
        KeyboardKey::F4 => "f4",
        KeyboardKey::F5 => "f5",
        KeyboardKey::F6 => "f6",
        KeyboardKey::F7 => "f7",
        KeyboardKey::F8 => "f8",
        KeyboardKey::F9 => "f9",
        KeyboardKey::F10 => "f10",
        KeyboardKey::F11 => "f11",
        KeyboardKey::F12 => "f12",
    }
}

pub fn keyboard_key_from_id(id: &str) -> Option<KeyboardKey> {
    editable_keys()
        .iter()
        .copied()
        .find(|key| keyboard_key_id(*key) == id)
}

#[cfg(test)]
#[path = "../../tests/settings/bindings/keys.rs"]
mod tests;
