use nerust_keyboard::Key;

const EDITABLE_KEYS: &[Key] = &[
    Key::KeyA,
    Key::KeyB,
    Key::KeyC,
    Key::KeyD,
    Key::KeyE,
    Key::KeyF,
    Key::KeyG,
    Key::KeyH,
    Key::KeyI,
    Key::KeyJ,
    Key::KeyK,
    Key::KeyL,
    Key::KeyM,
    Key::KeyN,
    Key::KeyO,
    Key::KeyP,
    Key::KeyQ,
    Key::KeyR,
    Key::KeyS,
    Key::KeyT,
    Key::KeyU,
    Key::KeyV,
    Key::KeyW,
    Key::KeyX,
    Key::KeyY,
    Key::KeyZ,
    Key::ArrowUp,
    Key::ArrowDown,
    Key::ArrowLeft,
    Key::ArrowRight,
    Key::Enter,
    Key::Escape,
    Key::Space,
    Key::Tab,
    Key::F1,
    Key::F2,
    Key::F3,
    Key::F4,
    Key::F5,
    Key::F6,
    Key::F7,
    Key::F8,
    Key::F9,
    Key::F10,
    Key::F11,
    Key::F12,
];

pub fn editable_keys() -> &'static [Key] {
    EDITABLE_KEYS
}

pub fn keyboard_key_label(key: Key) -> &'static str {
    match key {
        Key::KeyA => "A",
        Key::KeyB => "B",
        Key::KeyC => "C",
        Key::KeyD => "D",
        Key::KeyE => "E",
        Key::KeyF => "F",
        Key::KeyG => "G",
        Key::KeyH => "H",
        Key::KeyI => "I",
        Key::KeyJ => "J",
        Key::KeyK => "K",
        Key::KeyL => "L",
        Key::KeyM => "M",
        Key::KeyN => "N",
        Key::KeyO => "O",
        Key::KeyP => "P",
        Key::KeyQ => "Q",
        Key::KeyR => "R",
        Key::KeyS => "S",
        Key::KeyT => "T",
        Key::KeyU => "U",
        Key::KeyV => "V",
        Key::KeyW => "W",
        Key::KeyX => "X",
        Key::KeyY => "Y",
        Key::KeyZ => "Z",
        Key::Digit0 => "0",
        Key::Digit1 => "1",
        Key::Digit2 => "2",
        Key::Digit3 => "3",
        Key::Digit4 => "4",
        Key::Digit5 => "5",
        Key::Digit6 => "6",
        Key::Digit7 => "7",
        Key::Digit8 => "8",
        Key::Digit9 => "9",
        Key::ArrowUp => "Up",
        Key::ArrowDown => "Down",
        Key::ArrowLeft => "Left",
        Key::ArrowRight => "Right",
        Key::Enter => "Enter",
        Key::Escape => "Escape",
        Key::Space => "Space",
        Key::Tab => "Tab",
        Key::F1 => "F1",
        Key::F2 => "F2",
        Key::F3 => "F3",
        Key::F4 => "F4",
        Key::F5 => "F5",
        Key::F6 => "F6",
        Key::F7 => "F7",
        Key::F8 => "F8",
        Key::F9 => "F9",
        Key::F10 => "F10",
        Key::F11 => "F11",
        Key::F12 => "F12",
    }
}

pub fn keyboard_key_id(key: Key) -> &'static str {
    match key {
        Key::KeyA => "key_a",
        Key::KeyB => "key_b",
        Key::KeyC => "key_c",
        Key::KeyD => "key_d",
        Key::KeyE => "key_e",
        Key::KeyF => "key_f",
        Key::KeyG => "key_g",
        Key::KeyH => "key_h",
        Key::KeyI => "key_i",
        Key::KeyJ => "key_j",
        Key::KeyK => "key_k",
        Key::KeyL => "key_l",
        Key::KeyM => "key_m",
        Key::KeyN => "key_n",
        Key::KeyO => "key_o",
        Key::KeyP => "key_p",
        Key::KeyQ => "key_q",
        Key::KeyR => "key_r",
        Key::KeyS => "key_s",
        Key::KeyT => "key_t",
        Key::KeyU => "key_u",
        Key::KeyV => "key_v",
        Key::KeyW => "key_w",
        Key::KeyX => "key_x",
        Key::KeyY => "key_y",
        Key::KeyZ => "key_z",
        Key::Digit0 => "digit_0",
        Key::Digit1 => "digit_1",
        Key::Digit2 => "digit_2",
        Key::Digit3 => "digit_3",
        Key::Digit4 => "digit_4",
        Key::Digit5 => "digit_5",
        Key::Digit6 => "digit_6",
        Key::Digit7 => "digit_7",
        Key::Digit8 => "digit_8",
        Key::Digit9 => "digit_9",
        Key::ArrowUp => "arrow_up",
        Key::ArrowDown => "arrow_down",
        Key::ArrowLeft => "arrow_left",
        Key::ArrowRight => "arrow_right",
        Key::Enter => "enter",
        Key::Escape => "escape",
        Key::Space => "space",
        Key::Tab => "tab",
        Key::F1 => "f1",
        Key::F2 => "f2",
        Key::F3 => "f3",
        Key::F4 => "f4",
        Key::F5 => "f5",
        Key::F6 => "f6",
        Key::F7 => "f7",
        Key::F8 => "f8",
        Key::F9 => "f9",
        Key::F10 => "f10",
        Key::F11 => "f11",
        Key::F12 => "f12",
    }
}

#[cfg(test)]
mod tests {
    use nerust_keyboard::Key;

    use super::keyboard_key_label;

    #[test]
    fn keyboard_key_labels_are_human_readable() {
        assert_eq!(keyboard_key_label(Key::ArrowUp), "Up");
    }
}
