[workspace]
members = [
    "console",
    "core",
    "gui/gtk",
    "gui/glutin",
    "glwrap",
    "nes_ntsc",
    "screen/buffer",
    "screen/filter",
    "screen/opengl",
    "screen/traits",
    "serialize",
    "sound/openal",
    "sound/traits",
    "soundfilter",
    "timer"
]

[profile.release]
debug = true
