sonar.projectKey=chalharu_nerust
sonar.organization=chalharu
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=target/**,roms/**
sonar.rust.lcov.reportPaths=coverage/*.info
sonar.issue.ignore.multipleissues.per.issue=docker:S6471=1
