sonar.projectKey=chalharu_nerust
sonar.organization=chalharu
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=target/**,roms/**
sonar.rust.lcov.reportPaths=coverage/*.info
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=docker:S6471
sonar.issue.ignore.multicriteria.e1.resourceKey=.github/workflows/docker/Dockerfile.sonarcloud
