sonar.projectKey=chalharu_nerust
sonar.organization=chalharu
sonar.language=rs
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=target/**,roms/**
sonar.rust.lcov.reportPaths=coverage/lcov.info
