FROM rust:1.98.0-slim

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    clang mold \
    libgtk-3-dev \
    libgtk-4-dev \
    libepoxy-dev \
    libwebkit2gtk-4.1-dev \
    libxdo-dev \
    libasound2-dev \
    libcubeb-dev \
    libudev-dev \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

RUN rustup component add rustfmt clippy llvm-tools-preview

RUN cargo install cargo-llvm-cov --locked --version =0.8.7
