
FROM rust:1.98.0-slim AS builder
RUN cargo install cargo-llvm-cov --locked --version=0.8.7

FROM rust:1.98.0-slim

# hadolint ignore=DL3002
# NOSONAR
USER 0

# hadolint ignore=DL3008
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    clang \
    cmake \
    gnupg \
    libasound2-dev \
    libcubeb-dev \
    libepoxy-dev \
    libgtk-3-dev \
    libgtk-4-dev \
    libudev-dev \
    libwebkit2gtk-4.1-dev \
    libxdo-dev \
    make \
    mold \
    unzip \
    xauth \
    xvfb \
    && rm -rf /var/lib/apt/lists/* \
    && rustup component add rustfmt clippy llvm-tools-preview \
    && rm -rf /usr/local/cargo/registry/cache/* \
    && rm -rf /usr/local/cargo/registry/index/*

COPY --from=builder /usr/local/cargo/bin/cargo-llvm-cov /usr/local/cargo/bin/cargo-llvm-cov
