
FROM rust:1.99.0-slim@sha256:01dd4f9c24801cfc8ba9cf8a5dd6dcca451cd17d1ae73574edc22591de6e6816 AS builder
RUN cargo install cargo-llvm-cov --locked --version=0.8.7 \
    && cargo install cargo-nextest --locked --version=0.9.143 \
    --no-default-features --features=default-no-update

FROM rust:1.99.0-slim@sha256:01dd4f9c24801cfc8ba9cf8a5dd6dcca451cd17d1ae73574edc22591de6e6816

# hadolint ignore=DL3002
USER 0

# hadolint ignore=DL3008
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    clang \
    cmake \
    gnupg \
    libasound2-dev \
    libcubeb-dev \
    libepoxy-dev \
    libgtk-3-dev \
    libgtk-4-dev \
    libudev-dev \
    libwebkit2gtk-4.1-dev \
    libxdo-dev \
    make \
    mold \
    unzip \
    xauth \
    xvfb \
    && rm -rf /var/lib/apt/lists/* \
    && rustup component add rustfmt clippy llvm-tools-preview \
    && rm -rf /usr/local/cargo/registry/cache/* \
    && rm -rf /usr/local/cargo/registry/index/*

COPY --from=builder /usr/local/cargo/bin/cargo-llvm-cov /usr/local/cargo/bin/cargo-llvm-cov
COPY --from=builder /usr/local/cargo/bin/cargo-nextest /usr/local/cargo/bin/cargo-nextest
