pub mod error;
pub mod events;
// Canonical engine seam, crate-private: frontends drive systems only
// through `runner::{validate_case, measure_case}` behavior — never by
// holding a system handle. All construction/driving vocabulary lives
// behind this boundary; role views (`SystemControl`, `FrameObserve`,
// `SystemInspector`) are `pub(crate)` by the same rule.
mod factory_adapter;
pub mod harness;
pub mod manifest;
mod media;
pub mod report;
pub mod results;
pub mod runner;
mod serde_helpers;
#[cfg(test)]
mod tests;

// System factory list generated by build.rs from enabled features —
// the single source of truth shared with eligibility judgment.
// See `generated_system_factories.rs`.
include!(concat!(env!("OUT_DIR"), "/generated_system_factories.rs"));
