pub mod error;
pub mod events;
pub mod factory_adapter;
pub mod harness;
pub mod manifest;
mod media;
pub mod report;
pub mod results;
pub mod runner;
mod serde_helpers;
#[cfg(test)]
mod tests;

// System factory list generated by build.rs from enabled features —
// the single source of truth shared with eligibility judgment.
// See `generated_system_factories.rs`.
include!(concat!(env!("OUT_DIR"), "/generated_system_factories.rs"));
