[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "nerust_settings_core"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
nerust_core_traits.workspace = true
nerust_gui_settings.workspace = true
nerust_input_traits.workspace = true
nerust_keyboard.workspace = true
serde.workspace = true
typetag.workspace = true
