[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "nerust_gui_viewmodel"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
nerust_core_traits.workspace = true
nerust_gui_runtime.workspace = true
nerust_gui_settings.workspace = true
nerust_gui_shell.workspace = true
nerust_input_traits.workspace = true
nerust_keyboard.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde.workspace = true
typetag.workspace = true
