// Copyright (c) 2018 Mitsuharu Seki
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_path =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir")).join("rom_tests.yaml");
    println!("cargo::rerun-if-changed={}", manifest_path.display());

    let manifest_source =
        fs::read_to_string(&manifest_path).expect("ROM test manifest should be readable");
    let case_ids = manifest_source
        .lines()
        .filter_map(extract_case_id)
        .collect::<Vec<_>>();
    assert!(
        !case_ids.is_empty(),
        "ROM test manifest must contain at least one case id"
    );

    let mut generated = String::new();
    writeln!(
        generated,
        "// @generated by core/build.rs - do not edit manually.\n\
         const GENERATED_ROM_CASE_COUNT: usize = {};",
        case_ids.len()
    )
    .unwrap();

    for (index, case_id) in case_ids.iter().enumerate() {
        writeln!(
            generated,
            "#[test]\nfn {}() {{\n    run_generated_manifest_case({case_id:?});\n}}\n",
            test_name(index, case_id),
        )
        .unwrap();
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR should be available"));
    fs::write(out_dir.join("generated_rom_manifest_tests.rs"), generated)
        .expect("generated ROM tests should be written");
}

fn extract_case_id(line: &str) -> Option<String> {
    line.trim_start()
        .strip_prefix("- id: ")
        .map(|case_id| case_id.trim().to_string())
}

fn test_name(index: usize, case_id: &str) -> String {
    let mut name = format!("rom_case_{index:04}_");
    for character in case_id.chars() {
        if character.is_ascii_alphanumeric() {
            name.push(character.to_ascii_lowercase());
        } else {
            name.push('_');
        }
    }
    name
}
