[package]
name = "nerust_screen_filter"
version = "0.1.0"
authors = ["Mitsuharu Seki <mitsu1986@gmail.com>"]
edition = "2018"

[dependencies]
nerust_screen_traits = { version = ">=0.0.0", path="../traits" }
nes_ntsc = { version = ">=0.0.0", path="../../nes_ntsc" }
