#![cfg(feature = "iced")]

use iced::keyboard::key::Code;

use crate::{Key, error::KeyboardError};

impl TryFrom<Code> for Key {
    type Error = KeyboardError;

    fn try_from(code: Code) -> Result<Self, Self::Error> {
        match code {
            Code::Digit0 => Ok(Key::Digit0),
            Code::Digit1 => Ok(Key::Digit1),
            Code::Digit2 => Ok(Key::Digit2),
            Code::Digit3 => Ok(Key::Digit3),
            Code::Digit4 => Ok(Key::Digit4),
            Code::Digit5 => Ok(Key::Digit5),
            Code::Digit6 => Ok(Key::Digit6),
            Code::Digit7 => Ok(Key::Digit7),
            Code::Digit8 => Ok(Key::Digit8),
            Code::Digit9 => Ok(Key::Digit9),
            Code::KeyA => Ok(Key::KeyA),
            Code::KeyB => Ok(Key::KeyB),
            Code::KeyC => Ok(Key::KeyC),
            Code::KeyD => Ok(Key::KeyD),
            Code::KeyE => Ok(Key::KeyE),
            Code::KeyF => Ok(Key::KeyF),
            Code::KeyG => Ok(Key::KeyG),
            Code::KeyH => Ok(Key::KeyH),
            Code::KeyI => Ok(Key::KeyI),
            Code::KeyJ => Ok(Key::KeyJ),
            Code::KeyK => Ok(Key::KeyK),
            Code::KeyL => Ok(Key::KeyL),
            Code::KeyM => Ok(Key::KeyM),
            Code::KeyN => Ok(Key::KeyN),
            Code::KeyO => Ok(Key::KeyO),
            Code::KeyP => Ok(Key::KeyP),
            Code::KeyQ => Ok(Key::KeyQ),
            Code::KeyR => Ok(Key::KeyR),
            Code::KeyS => Ok(Key::KeyS),
            Code::KeyT => Ok(Key::KeyT),
            Code::KeyU => Ok(Key::KeyU),
            Code::KeyV => Ok(Key::KeyV),
            Code::KeyW => Ok(Key::KeyW),
            Code::KeyX => Ok(Key::KeyX),
            Code::KeyY => Ok(Key::KeyY),
            Code::KeyZ => Ok(Key::KeyZ),
            Code::ArrowUp => Ok(Key::ArrowUp),
            Code::ArrowDown => Ok(Key::ArrowDown),
            Code::ArrowLeft => Ok(Key::ArrowLeft),
            Code::ArrowRight => Ok(Key::ArrowRight),
            Code::Enter => Ok(Key::Enter),
            Code::Escape => Ok(Key::Escape),
            Code::Space => Ok(Key::Space),
            Code::Tab => Ok(Key::Tab),
            Code::F1 => Ok(Key::F1),
            Code::F2 => Ok(Key::F2),
            Code::F3 => Ok(Key::F3),
            Code::F4 => Ok(Key::F4),
            Code::F5 => Ok(Key::F5),
            Code::F6 => Ok(Key::F6),
            Code::F7 => Ok(Key::F7),
            Code::F8 => Ok(Key::F8),
            Code::F9 => Ok(Key::F9),
            Code::F10 => Ok(Key::F10),
            Code::F11 => Ok(Key::F11),
            Code::F12 => Ok(Key::F12),
            Code::Backspace => Ok(Key::Backspace),
            Code::Delete => Ok(Key::Delete),
            Code::Home => Ok(Key::Home),
            Code::End => Ok(Key::End),
            Code::ShiftLeft => Ok(Key::ShiftLeft),
            Code::ShiftRight => Ok(Key::ShiftRight),
            Code::ControlLeft => Ok(Key::ControlLeft),
            Code::ControlRight => Ok(Key::ControlRight),
            Code::AltLeft => Ok(Key::AltLeft),
            Code::AltRight => Ok(Key::AltRight),
            Code::Backquote => Ok(Key::Backquote),
            Code::NumpadEnter => Ok(Key::NumpadEnter),
            Code::Insert => Ok(Key::Insert),
            _ => Err(KeyboardError::KeyCodeConversionError(format!("{:?}", code))),
        }
    }
}

impl From<Key> for Code {
    fn from(key: Key) -> Self {
        match key {
            Key::Digit0 => Code::Digit0,
            Key::Digit1 => Code::Digit1,
            Key::Digit2 => Code::Digit2,
            Key::Digit3 => Code::Digit3,
            Key::Digit4 => Code::Digit4,
            Key::Digit5 => Code::Digit5,
            Key::Digit6 => Code::Digit6,
            Key::Digit7 => Code::Digit7,
            Key::Digit8 => Code::Digit8,
            Key::Digit9 => Code::Digit9,
            Key::KeyA => Code::KeyA,
            Key::KeyB => Code::KeyB,
            Key::KeyC => Code::KeyC,
            Key::KeyD => Code::KeyD,
            Key::KeyE => Code::KeyE,
            Key::KeyF => Code::KeyF,
            Key::KeyG => Code::KeyG,
            Key::KeyH => Code::KeyH,
            Key::KeyI => Code::KeyI,
            Key::KeyJ => Code::KeyJ,
            Key::KeyK => Code::KeyK,
            Key::KeyL => Code::KeyL,
            Key::KeyM => Code::KeyM,
            Key::KeyN => Code::KeyN,
            Key::KeyO => Code::KeyO,
            Key::KeyP => Code::KeyP,
            Key::KeyQ => Code::KeyQ,
            Key::KeyR => Code::KeyR,
            Key::KeyS => Code::KeyS,
            Key::KeyT => Code::KeyT,
            Key::KeyU => Code::KeyU,
            Key::KeyV => Code::KeyV,
            Key::KeyW => Code::KeyW,
            Key::KeyX => Code::KeyX,
            Key::KeyY => Code::KeyY,
            Key::KeyZ => Code::KeyZ,
            Key::ArrowUp => Code::ArrowUp,
            Key::ArrowDown => Code::ArrowDown,
            Key::ArrowLeft => Code::ArrowLeft,
            Key::ArrowRight => Code::ArrowRight,
            Key::Enter => Code::Enter,
            Key::Escape => Code::Escape,
            Key::Space => Code::Space,
            Key::Tab => Code::Tab,
            Key::F1 => Code::F1,
            Key::F2 => Code::F2,
            Key::F3 => Code::F3,
            Key::F4 => Code::F4,
            Key::F5 => Code::F5,
            Key::F6 => Code::F6,
            Key::F7 => Code::F7,
            Key::F8 => Code::F8,
            Key::F9 => Code::F9,
            Key::F10 => Code::F10,
            Key::F11 => Code::F11,
            Key::F12 => Code::F12,
            Key::Backspace => Code::Backspace,
            Key::Delete => Code::Delete,
            Key::Home => Code::Home,
            Key::End => Code::End,
            Key::ShiftLeft => Code::ShiftLeft,
            Key::ShiftRight => Code::ShiftRight,
            Key::ControlLeft => Code::ControlLeft,
            Key::ControlRight => Code::ControlRight,
            Key::AltLeft => Code::AltLeft,
            Key::AltRight => Code::AltRight,
            Key::Backquote => Code::Backquote,
            Key::NumpadEnter => Code::NumpadEnter,
            Key::Insert => Code::Insert,
        }
    }
}
