#![cfg(feature = "iced")]

use iced::keyboard::key::Code;

use crate::Key;

impl From<Code> for Key {
    fn from(code: Code) -> Self {
        match code {
            Code::Digit0 => Key::Digit0,
            Code::Digit1 => Key::Digit1,
            Code::Digit2 => Key::Digit2,
            Code::Digit3 => Key::Digit3,
            Code::Digit4 => Key::Digit4,
            Code::Digit5 => Key::Digit5,
            Code::Digit6 => Key::Digit6,
            Code::Digit7 => Key::Digit7,
            Code::Digit8 => Key::Digit8,
            Code::Digit9 => Key::Digit9,
            Code::KeyA => Key::KeyA,
            Code::KeyB => Key::KeyB,
            Code::KeyC => Key::KeyC,
            Code::KeyD => Key::KeyD,
            Code::KeyE => Key::KeyE,
            Code::KeyF => Key::KeyF,
            Code::KeyG => Key::KeyG,
            Code::KeyH => Key::KeyH,
            Code::KeyI => Key::KeyI,
            Code::KeyJ => Key::KeyJ,
            Code::KeyK => Key::KeyK,
            Code::KeyL => Key::KeyL,
            Code::KeyM => Key::KeyM,
            Code::KeyN => Key::KeyN,
            Code::KeyO => Key::KeyO,
            Code::KeyP => Key::KeyP,
            Code::KeyQ => Key::KeyQ,
            Code::KeyR => Key::KeyR,
            Code::KeyS => Key::KeyS,
            Code::KeyT => Key::KeyT,
            Code::KeyU => Key::KeyU,
            Code::KeyV => Key::KeyV,
            Code::KeyW => Key::KeyW,
            Code::KeyX => Key::KeyX,
            Code::KeyY => Key::KeyY,
            Code::KeyZ => Key::KeyZ,
            Code::ArrowUp => Key::ArrowUp,
            Code::ArrowDown => Key::ArrowDown,
            Code::ArrowLeft => Key::ArrowLeft,
            Code::ArrowRight => Key::ArrowRight,
            Code::Enter | Code::NumpadEnter => Key::Enter,
            Code::Escape => Key::Escape,
            Code::Space => Key::Space,
            Code::Tab => Key::Tab,
            Code::F1 => Key::F1,
            Code::F2 => Key::F2,
            Code::F3 => Key::F3,
            Code::F4 => Key::F4,
            Code::F5 => Key::F5,
            Code::F6 => Key::F6,
            Code::F7 => Key::F7,
            Code::F8 => Key::F8,
            Code::F9 => Key::F9,
            Code::F10 => Key::F10,
            Code::F11 => Key::F11,
            Code::F12 => Key::F12,
            _ => panic!("unrecognized iced Code: {code:?}"),
        }
    }
}
