mod error;
mod gdk;
mod iced;
mod tao;

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[cfg_attr(test, derive(strum::EnumIter))]
#[serde(rename_all = "snake_case")]
pub enum Key {
    // Letters
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,

    // Digits
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,

    //Function keys
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,

    // Navigation and editing
    Enter,
    Escape,
    Space,
    Tab,
    Delete,
    Backspace,
    Insert,
    CapsLock,
    Home,
    End,
    PageUp,
    PageDown,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,

    // Punctuation
    Minus,
    Equal,
    Plus,
    BracketLeft,
    BracketRight,
    Backslash,
    Semicolon,
    Quote,
    Backquote,
    Comma,
    Period,
    Slash,

    // Numpad
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadDecimal,
    NumpadAdd,
    NumpadSubtract,
    NumpadMultiply,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadComma,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,

    // Modifiers
    ControlLeft,
    ControlRight,
    ShiftLeft,
    ShiftRight,
    AltLeft,
    AltRight,
    SuperLeft,
    SuperRight,

    // Media keys
    AudioVolumeUp,
    AudioVolumeDown,
    AudioVolumeMute,
    MediaPlayPause,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    MediaSelect,

    // Browser keys
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,

    // System keys
    PrintScreen,
    ScrollLock,
    Pause,
    NumLock,
    ContextMenu,
    Power,
    Sleep,
    WakeUp,
    Eject,

    // Clipboard / editing keys
    Copy,
    Cut,
    Paste,
    Undo,
    Find,
    Help,
    Open,
    Select,
    Again,
    Props,
    Abort,
    Resume,
    Suspend,

    // Fn and legacy
    Fn,
    FnLock,
    Hyper,
    Turbo,

    // CJK / international
    Convert,
    NonConvert,
    KanaMode,
    Hiragana,
    Katakana,
    Lang1,
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    IntlBackslash,
    IntlRo,
    IntlYen,

    // App launch keys
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
}

impl Key {
    pub fn label(&self) -> &'static str {
        match self {
            Key::KeyA => "A",
            Key::KeyB => "B",
            Key::KeyC => "C",
            Key::KeyD => "D",
            Key::KeyE => "E",
            Key::KeyF => "F",
            Key::KeyG => "G",
            Key::KeyH => "H",
            Key::KeyI => "I",
            Key::KeyJ => "J",
            Key::KeyK => "K",
            Key::KeyL => "L",
            Key::KeyM => "M",
            Key::KeyN => "N",
            Key::KeyO => "O",
            Key::KeyP => "P",
            Key::KeyQ => "Q",
            Key::KeyR => "R",
            Key::KeyS => "S",
            Key::KeyT => "T",
            Key::KeyU => "U",
            Key::KeyV => "V",
            Key::KeyW => "W",
            Key::KeyX => "X",
            Key::KeyY => "Y",
            Key::KeyZ => "Z",
            Key::Digit0 => "0",
            Key::Digit1 => "1",
            Key::Digit2 => "2",
            Key::Digit3 => "3",
            Key::Digit4 => "4",
            Key::Digit5 => "5",
            Key::Digit6 => "6",
            Key::Digit7 => "7",
            Key::Digit8 => "8",
            Key::Digit9 => "9",
            Key::ArrowUp => "↑",
            Key::ArrowDown => "↓",
            Key::ArrowLeft => "←",
            Key::ArrowRight => "→",
            Key::Enter => "Enter",
            Key::Escape => "Esc",
            Key::Space => "Space",
            Key::Tab => "Tab",
            Key::F1 => "F1",
            Key::F2 => "F2",
            Key::F3 => "F3",
            Key::F4 => "F4",
            Key::F5 => "F5",
            Key::F6 => "F6",
            Key::F7 => "F7",
            Key::F8 => "F8",
            Key::F9 => "F9",
            Key::F10 => "F10",
            Key::F11 => "F11",
            Key::F12 => "F12",
            Key::Backspace => "Backspace",
            Key::Delete => "Delete",
            Key::Home => "Home",
            Key::End => "End",
            Key::ShiftLeft => "Shift(L)",
            Key::ShiftRight => "Shift(R)",
            Key::ControlLeft => "Ctrl(L)",
            Key::ControlRight => "Ctrl(R)",
            Key::AltLeft => "Alt(L)",
            Key::AltRight => "Alt(R)",
            Key::Backquote => "`",
            Key::Comma => ",",
            Key::Period => ".",
            Key::Slash => "/",
            Key::Semicolon => ";",
            Key::Quote => "'",
            Key::BracketLeft => "[",
            Key::BracketRight => "]",
            Key::Backslash => "\\",
            Key::Minus => "-",
            Key::Equal => "=",
            Key::IntlBackslash => "\\(Intl)",
            Key::PageUp => "PgUp",
            Key::PageDown => "PgDn",
            Key::CapsLock => "Caps",
            Key::ScrollLock => "Scrlk",
            Key::Pause => "Pause",
            Key::PrintScreen => "PrtSc",
            Key::Convert => "Convert",
            Key::NonConvert => "NonConv",
            Key::Hiragana => "Hiragana",
            Key::Katakana => "Katakana",
            Key::KanaMode => "Kana",
            Key::IntlRo => "ろ",
            Key::IntlYen => "¥",
            Key::Numpad0 => "Num0",
            Key::Numpad1 => "Num1",
            Key::Numpad2 => "Num2",
            Key::Numpad3 => "Num3",
            Key::Numpad4 => "Num4",
            Key::Numpad5 => "Num5",
            Key::Numpad6 => "Num6",
            Key::Numpad7 => "Num7",
            Key::Numpad8 => "Num8",
            Key::Numpad9 => "Num9",
            Key::NumpadEnter => "NumEnter",
            Key::NumpadDecimal => "Num.",
            Key::NumpadAdd => "Num+",
            Key::NumpadSubtract => "Num-",
            Key::NumpadMultiply => "Num*",
            Key::NumpadDivide => "Num/",
            Key::Insert => "Insert",
            Key::F13 => "F13",
            Key::F14 => "F14",
            Key::F15 => "F15",
            Key::F16 => "F16",
            Key::F17 => "F17",
            Key::F18 => "F18",
            Key::F19 => "F19",
            Key::F20 => "F20",
            Key::F21 => "F21",
            Key::F22 => "F22",
            Key::F23 => "F23",
            Key::F24 => "F24",
            Key::F25 => "F25",
            Key::F26 => "F26",
            Key::F27 => "F27",
            Key::F28 => "F28",
            Key::F29 => "F29",
            Key::F30 => "F30",
            Key::F31 => "F31",
            Key::F32 => "F32",
            Key::F33 => "F33",
            Key::F34 => "F34",
            Key::F35 => "F35",
            Key::Plus => "+",
            Key::NumpadEqual => "Num=",
            Key::NumpadComma => "Num,",
            Key::NumpadBackspace => "NumBS",
            Key::NumpadClear => "NumClr",
            Key::NumpadClearEntry => "NumCE",
            Key::NumpadHash => "Num#",
            Key::NumpadMemoryAdd => "NumM+",
            Key::NumpadMemoryClear => "NumMC",
            Key::NumpadMemoryRecall => "NumMR",
            Key::NumpadMemoryStore => "NumMS",
            Key::NumpadMemorySubtract => "NumM-",
            Key::NumpadParenLeft => "Num(",
            Key::NumpadParenRight => "Num)",
            Key::NumpadStar => "Num*",
            Key::SuperLeft => "Super(L)",
            Key::SuperRight => "Super(R)",
            Key::AudioVolumeUp => "Vol+",
            Key::AudioVolumeDown => "Vol-",
            Key::AudioVolumeMute => "VolM",
            Key::MediaPlayPause => "Play/Pause",
            Key::MediaStop => "Stop",
            Key::MediaTrackNext => "Next",
            Key::MediaTrackPrevious => "Previous",
            Key::MediaSelect => "MediaSelect",
            Key::BrowserBack => "Back",
            Key::BrowserFavorites => "Favorites",
            Key::BrowserForward => "Forward",
            Key::BrowserHome => "Home",
            Key::BrowserRefresh => "Refresh",
            Key::BrowserSearch => "Search",
            Key::BrowserStop => "Stop",
            Key::NumLock => "NumLock",
            Key::ContextMenu => "Menu",
            Key::Power => "Power",
            Key::Sleep => "Sleep",
            Key::WakeUp => "WakeUp",
            Key::Eject => "Eject",
            Key::Copy => "Copy",
            Key::Cut => "Cut",
            Key::Paste => "Paste",
            Key::Undo => "Undo",
            Key::Find => "Find",
            Key::Help => "Help",
            Key::Open => "Open",
            Key::Select => "Select",
            Key::Again => "Again",
            Key::Props => "Props",
            Key::Abort => "Abort",
            Key::Resume => "Resume",
            Key::Suspend => "Suspend",
            Key::Fn => "Fn",
            Key::FnLock => "FnLock",
            Key::Hyper => "Hyper",
            Key::Turbo => "Turbo",
            Key::Lang1 => "Kana",
            Key::Lang2 => "Eisu",
            Key::Lang3 => "Katakana",
            Key::Lang4 => "Hiragana",
            Key::Lang5 => "Zenkaku/Hankaku",
            Key::LaunchApp1 => "LaunchApp1",
            Key::LaunchApp2 => "LaunchApp2",
            Key::LaunchMail => "LaunchMail",
        }
    }
}
