#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Key {
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    Enter,
    Escape,
    Space,
    Tab,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
}

#[cfg(feature = "tao")]
mod tao_impl {
    use crate::Key;

    impl From<tao::keyboard::KeyCode> for Key {
        fn from(code: tao::keyboard::KeyCode) -> Self {
            match code {
                tao::keyboard::KeyCode::KeyA => Key::KeyA,
                tao::keyboard::KeyCode::KeyB => Key::KeyB,
                tao::keyboard::KeyCode::KeyC => Key::KeyC,
                tao::keyboard::KeyCode::KeyD => Key::KeyD,
                tao::keyboard::KeyCode::KeyE => Key::KeyE,
                tao::keyboard::KeyCode::KeyF => Key::KeyF,
                tao::keyboard::KeyCode::KeyG => Key::KeyG,
                tao::keyboard::KeyCode::KeyH => Key::KeyH,
                tao::keyboard::KeyCode::KeyI => Key::KeyI,
                tao::keyboard::KeyCode::KeyJ => Key::KeyJ,
                tao::keyboard::KeyCode::KeyK => Key::KeyK,
                tao::keyboard::KeyCode::KeyL => Key::KeyL,
                tao::keyboard::KeyCode::KeyM => Key::KeyM,
                tao::keyboard::KeyCode::KeyN => Key::KeyN,
                tao::keyboard::KeyCode::KeyO => Key::KeyO,
                tao::keyboard::KeyCode::KeyP => Key::KeyP,
                tao::keyboard::KeyCode::KeyQ => Key::KeyQ,
                tao::keyboard::KeyCode::KeyR => Key::KeyR,
                tao::keyboard::KeyCode::KeyS => Key::KeyS,
                tao::keyboard::KeyCode::KeyT => Key::KeyT,
                tao::keyboard::KeyCode::KeyU => Key::KeyU,
                tao::keyboard::KeyCode::KeyV => Key::KeyV,
                tao::keyboard::KeyCode::KeyW => Key::KeyW,
                tao::keyboard::KeyCode::KeyX => Key::KeyX,
                tao::keyboard::KeyCode::KeyY => Key::KeyY,
                tao::keyboard::KeyCode::KeyZ => Key::KeyZ,
                tao::keyboard::KeyCode::Digit0 => Key::Digit0,
                tao::keyboard::KeyCode::Digit1 => Key::Digit1,
                tao::keyboard::KeyCode::Digit2 => Key::Digit2,
                tao::keyboard::KeyCode::Digit3 => Key::Digit3,
                tao::keyboard::KeyCode::Digit4 => Key::Digit4,
                tao::keyboard::KeyCode::Digit5 => Key::Digit5,
                tao::keyboard::KeyCode::Digit6 => Key::Digit6,
                tao::keyboard::KeyCode::Digit7 => Key::Digit7,
                tao::keyboard::KeyCode::Digit8 => Key::Digit8,
                tao::keyboard::KeyCode::Digit9 => Key::Digit9,
                tao::keyboard::KeyCode::ArrowUp => Key::ArrowUp,
                tao::keyboard::KeyCode::ArrowDown => Key::ArrowDown,
                tao::keyboard::KeyCode::ArrowLeft => Key::ArrowLeft,
                tao::keyboard::KeyCode::ArrowRight => Key::ArrowRight,
                tao::keyboard::KeyCode::Enter => Key::Enter,
                tao::keyboard::KeyCode::Escape => Key::Escape,
                tao::keyboard::KeyCode::Space => Key::Space,
                tao::keyboard::KeyCode::Tab => Key::Tab,
                tao::keyboard::KeyCode::F1 => Key::F1,
                tao::keyboard::KeyCode::F2 => Key::F2,
                tao::keyboard::KeyCode::F3 => Key::F3,
                tao::keyboard::KeyCode::F4 => Key::F4,
                tao::keyboard::KeyCode::F5 => Key::F5,
                tao::keyboard::KeyCode::F6 => Key::F6,
                tao::keyboard::KeyCode::F7 => Key::F7,
                tao::keyboard::KeyCode::F8 => Key::F8,
                tao::keyboard::KeyCode::F9 => Key::F9,
                tao::keyboard::KeyCode::F10 => Key::F10,
                tao::keyboard::KeyCode::F11 => Key::F11,
                tao::keyboard::KeyCode::F12 => Key::F12,
                _ => panic!("unrecognized tao KeyCode: {code:?}"),
            }
        }
    }
}

#[cfg(feature = "gdk")]
mod gdk_impl {
    use crate::Key;

    impl From<gdk::Key> for Key {
        fn from(key: gdk::Key) -> Self {
            match key {
                gdk::Key::_0 => Key::Digit0,
                gdk::Key::_1 => Key::Digit1,
                gdk::Key::_2 => Key::Digit2,
                gdk::Key::_3 => Key::Digit3,
                gdk::Key::_4 => Key::Digit4,
                gdk::Key::_5 => Key::Digit5,
                gdk::Key::_6 => Key::Digit6,
                gdk::Key::_7 => Key::Digit7,
                gdk::Key::_8 => Key::Digit8,
                gdk::Key::_9 => Key::Digit9,
                gdk::Key::a | gdk::Key::A => Key::KeyA,
                gdk::Key::b | gdk::Key::B => Key::KeyB,
                gdk::Key::c | gdk::Key::C => Key::KeyC,
                gdk::Key::d | gdk::Key::D => Key::KeyD,
                gdk::Key::e | gdk::Key::E => Key::KeyE,
                gdk::Key::f | gdk::Key::F => Key::KeyF,
                gdk::Key::g | gdk::Key::G => Key::KeyG,
                gdk::Key::h | gdk::Key::H => Key::KeyH,
                gdk::Key::i | gdk::Key::I => Key::KeyI,
                gdk::Key::j | gdk::Key::J => Key::KeyJ,
                gdk::Key::k | gdk::Key::K => Key::KeyK,
                gdk::Key::l | gdk::Key::L => Key::KeyL,
                gdk::Key::m | gdk::Key::M => Key::KeyM,
                gdk::Key::n | gdk::Key::N => Key::KeyN,
                gdk::Key::o | gdk::Key::O => Key::KeyO,
                gdk::Key::p | gdk::Key::P => Key::KeyP,
                gdk::Key::q | gdk::Key::Q => Key::KeyQ,
                gdk::Key::r | gdk::Key::R => Key::KeyR,
                gdk::Key::s | gdk::Key::S => Key::KeyS,
                gdk::Key::t | gdk::Key::T => Key::KeyT,
                gdk::Key::u | gdk::Key::U => Key::KeyU,
                gdk::Key::v | gdk::Key::V => Key::KeyV,
                gdk::Key::w | gdk::Key::W => Key::KeyW,
                gdk::Key::x | gdk::Key::X => Key::KeyX,
                gdk::Key::y | gdk::Key::Y => Key::KeyY,
                gdk::Key::z | gdk::Key::Z => Key::KeyZ,
                gdk::Key::Up => Key::ArrowUp,
                gdk::Key::Down => Key::ArrowDown,
                gdk::Key::Left => Key::ArrowLeft,
                gdk::Key::Right => Key::ArrowRight,
                gdk::Key::Return | gdk::Key::ISO_Enter | gdk::Key::KP_Enter => Key::Enter,
                gdk::Key::Escape => Key::Escape,
                gdk::Key::space => Key::Space,
                gdk::Key::Tab | gdk::Key::ISO_Left_Tab | gdk::Key::KP_Tab => Key::Tab,
                gdk::Key::F1 => Key::F1,
                gdk::Key::F2 => Key::F2,
                gdk::Key::F3 => Key::F3,
                gdk::Key::F4 => Key::F4,
                gdk::Key::F5 => Key::F5,
                gdk::Key::F6 => Key::F6,
                gdk::Key::F7 => Key::F7,
                gdk::Key::F8 => Key::F8,
                gdk::Key::F9 => Key::F9,
                gdk::Key::F10 => Key::F10,
                gdk::Key::F11 => Key::F11,
                gdk::Key::F12 => Key::F12,
                _ => panic!("unrecognized gdk Key: {key:?}"),
            }
        }
    }
}
