use std::{collections::BTreeSet, env, fmt::Write as _, fs, path::PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    rom_root: PathBuf,
    suites: Vec<Suite>,
}

#[derive(Deserialize)]
struct Suite {
    name: String,
    #[serde(default)]
    cases: Vec<Case>,
    #[serde(default)]
    case_patterns: Vec<CasePattern>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    rom: String,
}

#[derive(Deserialize)]
struct CasePattern {
    glob: String,
    #[serde(default)]
    exclude_globs: Vec<String>,
    #[serde(default)]
    id_prefix: String,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_path = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?).join("rom_tests.yaml");
    println!("cargo::rerun-if-changed={}", manifest_path.display());

    let manifest_source = fs::read_to_string(&manifest_path)
        .map_err(|error| format!("failed to read {}: {error}", manifest_path.display()))?;
    let manifest: Manifest = serde_saphyr::from_str(&manifest_source)
        .map_err(|error| format!("invalid YAML in {}: {error}", manifest_path.display()))?;
    let manifest_dir = manifest_path
        .parent()
        .ok_or("manifest has no parent directory")?;
    let rom_root = manifest_dir.join(&manifest.rom_root);
    println!("cargo::rerun-if-changed={}", rom_root.display());
    let mut cases = Vec::new();
    for mut suite in manifest.suites {
        let suite_dir = rom_root.join(&suite.name);
        let mut matched_paths = BTreeSet::new();
        for pattern in suite.case_patterns {
            let absolute_pattern = suite_dir.join(&pattern.glob);
            let exclude_patterns = pattern
                .exclude_globs
                .iter()
                .map(|exclude| {
                    glob::Pattern::new(exclude).map_err(|error| {
                        std::io::Error::other(format!(
                            "invalid exclude glob `{exclude}` in suite `{}`: {error}",
                            suite.name
                        ))
                    })
                })
                .collect::<Result<Vec<_>, _>>()?;
            let paths = glob::glob(&absolute_pattern.to_string_lossy()).map_err(|error| {
                std::io::Error::other(format!(
                    "invalid case glob `{}` in suite `{}`: {error}",
                    pattern.glob, suite.name
                ))
            })?;
            for path in paths {
                let path = path.map_err(|error| {
                    std::io::Error::other(format!(
                        "failed to read case glob `{}` in suite `{}`: {error}",
                        pattern.glob, suite.name
                    ))
                })?;
                let relative = path.strip_prefix(&suite_dir).map_err(|_| {
                    std::io::Error::other(format!(
                        "glob `{}` matched outside suite `{}`",
                        pattern.glob, suite.name
                    ))
                })?;
                if exclude_patterns
                    .iter()
                    .any(|pattern| pattern.matches_path(relative))
                    || !matched_paths.insert(path.clone())
                {
                    continue;
                }
                let stem = path
                    .file_stem()
                    .and_then(|stem| stem.to_str())
                    .ok_or_else(|| {
                        std::io::Error::other(format!("ROM path is not UTF-8: {}", path.display()))
                    })?;
                suite.cases.push(Case {
                    id: format!("{}{}", pattern.id_prefix, stem),
                    rom: relative.to_string_lossy().into_owned(),
                });
            }
        }
        cases.extend(
            suite
                .cases
                .into_iter()
                .map(|case| (suite.name.clone(), case)),
        );
    }
    if cases.is_empty() {
        return Err("ROM test manifest must contain at least one case".into());
    }

    let mut generated = String::new();
    writeln!(
        generated,
        "// @generated by gba/rom_test/build.rs - do not edit manually."
    )?;

    for (index, (suite, case)) in cases.iter().enumerate() {
        let rom_exists = rom_root.join(suite).join(&case.rom).is_file();
        let ignore = if rom_exists {
            String::new()
        } else {
            "#[ignore = \"ROM asset is not available\"]\n".to_string()
        };
        writeln!(
            generated,
            "#[test]\n{ignore}fn {}() {{\n    crate::run_generated_manifest_case({:?});\n}}\n",
            test_name(index, &case.id),
            case.id
        )?;
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    fs::write(out_dir.join("generated_rom_manifest_tests.rs"), generated)?;
    Ok(())
}

fn test_name(index: usize, case_id: &str) -> String {
    let mut name = format!("rom_case_{index:04}_");
    for character in case_id.chars() {
        if character.is_ascii_alphanumeric() {
            name.push(character.to_ascii_lowercase());
        } else {
            name.push('_');
        }
    }
    name.truncate(120);
    name
}
