//! Generate one Rust test per ROM case so nextest can schedule and report cases independently.
//!
//! Filesystem pattern expansion is shared with the runtime manifest loader. This keeps build-time
//! discovery and CLI execution consistent without duplicating the glob implementation.

use std::{env, fmt::Write as _, fs, path::PathBuf};

use serde::{Deserialize, Deserializer};

#[path = "src/case_expansion.rs"]
mod case_expansion;

#[derive(Deserialize)]
struct BuildManifest {
    rom_root: PathBuf,
    suites: Vec<BuildSuite>,
}

#[derive(Deserialize)]
struct BuildSuite {
    name: String,
    #[serde(default)]
    cases: Vec<BuildCase>,
    #[serde(default)]
    case_patterns: Vec<BuildPattern>,
}

#[derive(Deserialize)]
struct BuildCase {
    id: String,
    rom: String,
    #[serde(rename = "verify", default, deserialize_with = "deserialize_present")]
    has_verify: bool,
    #[serde(default)]
    reference: Option<String>,
}

#[derive(Deserialize)]
struct BuildPattern {
    glob: String,
    #[serde(default)]
    exclude_globs: Vec<String>,
    #[serde(default)]
    id_prefix: String,
}

type BuildCases = Vec<(String, BuildCase)>;
type BuildResult<T> = Result<T, Box<dyn std::error::Error>>;

fn main() -> BuildResult<()> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let manifest_path = manifest_dir.join("rom_tests.yaml");
    println!("cargo::rerun-if-changed={}", manifest_path.display());
    let (rom_root, cases) = load_cases(&manifest_path)?;
    println!("cargo::rerun-if-changed={}", rom_root.display());
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    fs::write(
        out_dir.join("generated_rom_manifest_tests.rs"),
        generate_tests(&rom_root, &cases)?,
    )?;
    Ok(())
}

fn load_cases(manifest_path: &std::path::Path) -> BuildResult<(PathBuf, BuildCases)> {
    let source = fs::read_to_string(manifest_path)?;
    let manifest: BuildManifest = serde_saphyr::from_str(&source)?;
    let manifest_dir = manifest_path
        .parent()
        .unwrap_or_else(|| std::path::Path::new("."));
    let rom_root = manifest_dir.join(manifest.rom_root);
    let mut cases = Vec::new();
    for mut suite in manifest.suites {
        append_pattern_cases(&rom_root, &mut suite)?;
        cases.extend(
            suite
                .cases
                .into_iter()
                .map(|case| (suite.name.clone(), case)),
        );
    }
    require_case_files(&rom_root, &cases)?;
    Ok((rom_root, cases))
}

fn require_case_files(
    rom_root: &std::path::Path,
    cases: &[(String, BuildCase)],
) -> BuildResult<()> {
    if let Some((suite, case)) = cases
        .iter()
        .find(|(suite, case)| !rom_root.join(suite).join(&case.rom).is_file())
    {
        return Err(format!(
            "ROM case `{}` is missing file {}",
            case.id,
            rom_root.join(suite).join(&case.rom).display()
        )
        .into());
    }
    Ok(())
}

fn append_pattern_cases(rom_root: &std::path::Path, suite: &mut BuildSuite) -> BuildResult<()> {
    let patterns = suite
        .case_patterns
        .iter()
        .map(|pattern| case_expansion::CasePatternRef {
            glob: &pattern.glob,
            exclude_globs: &pattern.exclude_globs,
            id_prefix: &pattern.id_prefix,
        })
        .collect::<Vec<_>>();
    let expanded = case_expansion::expand_case_patterns(&rom_root.join(&suite.name), &patterns)
        .map_err(std::io::Error::other)?;
    suite.cases.extend(expanded.into_iter().map(|case| {
        // Runtime uses these fields to apply pattern defaults and descriptions.
        let _runtime_metadata = (case.pattern_index, case.description);
        BuildCase {
            id: case.id,
            rom: case.rom,
            has_verify: false,
            reference: None,
        }
    }));
    suite.cases.sort_by(|left, right| left.id.cmp(&right.id));
    Ok(())
}

fn generate_tests(
    rom_root: &std::path::Path,
    cases: &[(String, BuildCase)],
) -> Result<String, std::fmt::Error> {
    let mut generated = String::from("// @generated by gba/rom_test/build.rs - do not edit.\n\n");
    for (index, (suite, case)) in cases.iter().enumerate() {
        let has_reference = case.reference.is_some()
            || rom_root
                .join(suite)
                .join(&case.rom)
                .with_extension("png")
                .is_file()
            || rom_root
                .join(suite)
                .join(&case.rom)
                .parent()
                .is_some_and(|dir| dir.join("expected.png").is_file() || dir.join("expected.jpg").is_file());
        let ignore = !case.has_verify && !has_reference;
        writeln!(
            generated,
            "#[test]{}\nfn {}() {{ crate::run_generated_manifest_case({:?}); }}\n",
            if ignore { "\n#[ignore = \"case has no verification\"]" } else { "" },
            test_name(index, &case.id),
            case.id
        )?;
    }
    Ok(generated)
}

fn deserialize_present<'de, D>(deserializer: D) -> Result<bool, D::Error>
where
    D: Deserializer<'de>,
{
    let _ = serde::de::IgnoredAny::deserialize(deserializer)?;
    Ok(true)
}

/// Include a stable index so sanitized or truncated case IDs can never collide.
fn test_name(index: usize, case_id: &str) -> String {
    let mut name = format!("rom_case_{index:04}_");
    name.extend(case_id.chars().map(|character| {
        if character.is_ascii_alphanumeric() {
            character.to_ascii_lowercase()
        } else {
            '_'
        }
    }));
    name.truncate(120);
    name
}
