use std::{env, fmt::Write as _, fs, path::PathBuf};

struct RomCaseSpec {
    id: String,
    ci: bool,
    rom: String,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let manifest_path = manifest_dir.join("rom_tests.yaml");
    println!("cargo::rerun-if-changed={}", manifest_path.display());
    // Re-run generation when the CI gate changes.
    println!("cargo::rerun-if-env-changed=NERUST_ROM_CI");

    let manifest_source =
        fs::read_to_string(&manifest_path).expect("ROM test manifest should be readable");
    let rom_root = extract_rom_root(&manifest_source);
    let cases = parse_cases(&manifest_source);
    assert!(
        !cases.is_empty(),
        "ROM test manifest must contain at least one case id"
    );

    // In CI (`NERUST_ROM_CI` set), only `ci`-flagged cases with a
    // checked-out ROM run. Locally, every checked-out ROM runs.
    // Anything else becomes `#[ignore]` instead of failing (P3:
    // sparse checkouts must skip, not fail).
    let ci_mode = env::var("NERUST_ROM_CI").is_ok_and(|value| !value.is_empty());
    // System factories come from crate features. Single source of
    // truth, used both for generating the factory list below and for
    // eligibility judgment: without any system, no case is eligible,
    // so everything becomes `#[ignore]` instead of failing — the same
    // judgment `validate` reports at runtime as ignored. Add GBC/GBA
    // rows here; nothing else needs to learn new systems.
    let systems: &[(&str, &str)] = &[(
        "CARGO_FEATURE_NES",
        "nerust_nes_factory::NesFactory::boxed()",
    )];
    let mut factory_items = String::new();
    let mut has_system = false;
    for (feature_env, construct) in systems {
        // Re-run when any system feature toggles, so the generated
        // list and eligibility never go stale. Emitted from the table
        // itself: adding a system touches nothing else.
        println!("cargo::rerun-if-env-changed={feature_env}");
        if env::var(feature_env).is_ok() {
            has_system = true;
            writeln!(factory_items, "        {construct},").unwrap();
        }
    }
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR should be available"));
    fs::write(
        out_dir.join("generated_system_factories.rs"),
        format!(
            "// @generated by rom_test/build.rs - do not edit manually.\n\
             /// System factories available to headless drivers: one boxed\n\
             /// `dyn CoreFactory` per enabled system feature. Empty without\n\
             /// features — drivers then ignore every case instead of failing.\n\
             pub fn system_factories() -> Vec<Box<dyn nerust_core_traits::factory::CoreFactory>> {{\n\
             \x20   vec![\n{factory_items}\x20   ]\n\
             }}\n"
        ),
    )
    .expect("generated system factories should be written");

    let mut generated = String::new();
    writeln!(
        generated,
        "// @generated by rom_test/build.rs - do not edit manually.\n\
         const GENERATED_ROM_CASE_COUNT: usize = {};",
        cases.len()
    )
    .unwrap();

    for (index, case) in cases.iter().enumerate() {
        let rom_path = manifest_dir.join(&rom_root).join(&case.rom);
        let mut skip_reason: Option<String> = None;
        if !has_system {
            skip_reason = Some("no system cores enabled".to_string());
        } else if !rom_path.is_file() {
            skip_reason = Some(format!("ROM missing: {}", case.rom));
        } else if ci_mode && !case.ci {
            skip_reason = Some("not in CI scope (ci: false)".to_string());
        }
        let name = test_name(index, &case.id);
        match skip_reason {
            Some(reason) => writeln!(
                generated,
                "#[test]\n#[ignore = \"{reason}\"]\nfn {name}() {{\n    run_generated_manifest_case({:?});\n}}\n",
                case.id,
            )
            .unwrap(),
            None => writeln!(
                generated,
                "#[test]\nfn {name}() {{\n    run_generated_manifest_case({:?});\n}}\n",
                case.id,
            )
            .unwrap(),
        }
    }

    fs::write(out_dir.join("generated_rom_manifest_tests.rs"), generated)
        .expect("generated ROM tests should be written");
}

fn extract_rom_root(source: &str) -> String {
    source
        .lines()
        .filter_map(|line| line.strip_prefix("rom_root: "))
        .map(|root| root.trim().to_string())
        .next()
        .expect("ROM manifest must declare rom_root")
}

fn parse_cases(source: &str) -> Vec<RomCaseSpec> {
    let mut cases = Vec::new();
    let mut current: Option<RomCaseSpec> = None;
    for line in source.lines() {
        let trimmed = line.trim_start();
        if let Some(id) = trimmed.strip_prefix("- id: ") {
            take_current(&mut current, &mut cases);
            current = Some(RomCaseSpec {
                id: id.trim().to_string(),
                ci: true,
                rom: String::new(),
            });
        } else if let Some(rest) = trimmed.strip_prefix("ci:") {
            if let Some(case) = current.as_mut() {
                case.ci = rest.trim() != "false";
            }
        } else if let Some(rest) = trimmed.strip_prefix("rom:")
            && let Some(case) = current.as_mut()
            && case.rom.is_empty()
        {
            case.rom = rest.trim().to_string();
        }
    }
    take_current(&mut current, &mut cases);
    cases
}

fn take_current(current: &mut Option<RomCaseSpec>, cases: &mut Vec<RomCaseSpec>) {
    if let Some(case) = current.take() {
        cases.push(case);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_cases_tracks_ci_and_rom_per_case() {
        let source = [
            "rom_root: ../roms",
            "cases:",
            "  - id: a.first",
            "    rom: a.nes",
            "  - id: b.second",
            "    rom: b.nes",
            "    ci: false",
        ]
        .join("\n");
        let cases = parse_cases(&source);
        assert_eq!(cases.len(), 2);
        assert_eq!(cases[0].id, "a.first");
        assert!(cases[0].ci);
        assert_eq!(cases[0].rom, "a.nes");
        assert!(!cases[1].ci);
        assert_eq!(cases[1].rom, "b.nes");
    }
}

fn test_name(index: usize, case_id: &str) -> String {
    let mut name = format!("rom_case_{index:04}_");
    for character in case_id.chars() {
        if character.is_ascii_alphanumeric() {
            name.push(character.to_ascii_lowercase());
        } else {
            name.push('_');
        }
    }
    name
}
