use std::{env, fmt::Write as _, fs, path::PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    suites: Vec<Suite>,
}

#[derive(Deserialize)]
struct Suite {
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    models: Vec<String>,
}

fn main() {
    let manifest_path =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir")).join("rom_tests.yaml");
    println!("cargo::rerun-if-changed={}", manifest_path.display());

    let manifest_source =
        fs::read_to_string(&manifest_path).expect("ROM test manifest should be readable");
    let manifest: Manifest =
        serde_saphyr::from_str(&manifest_source).expect("ROM test manifest should be valid YAML");
    let cells = manifest
        .suites
        .into_iter()
        .flat_map(|suite| suite.cases)
        .flat_map(|case| {
            case.models
                .into_iter()
                .map(move |model| (case.id.clone(), model))
        })
        .collect::<Vec<_>>();
    assert!(
        !cells.is_empty(),
        "ROM test manifest must contain at least one matrix cell"
    );

    let mut generated = String::new();
    writeln!(
        generated,
        "// @generated by gbc/rom_test/build.rs - do not edit manually.\n\
         const GENERATED_ROM_CELL_COUNT: usize = {};",
        cells.len()
    )
    .unwrap();

    for (index, (case_id, model)) in cells.iter().enumerate() {
        writeln!(
            generated,
            "#[test]\nfn {}() {{\n    run_generated_manifest_cell({case_id:?}, {model:?});\n}}\n",
            test_name(index, case_id, model),
        )
        .unwrap();
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR should be available"));
    fs::write(out_dir.join("generated_rom_manifest_tests.rs"), generated)
        .expect("generated ROM tests should be written");
}

fn test_name(index: usize, case_id: &str, model: &str) -> String {
    let mut name = format!("rom_case_{index:04}_");
    for character in case_id.chars().chain(['_']).chain(model.chars()) {
        if character.is_ascii_alphanumeric() {
            name.push(character.to_ascii_lowercase());
        } else {
            name.push('_');
        }
    }
    name
}
