use std::{collections::BTreeSet, env, fmt::Write as _, fs, path::PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    rom_root: PathBuf,
    suites: Vec<Suite>,
}

#[derive(Deserialize)]
struct Suite {
    name: String,
    #[serde(default)]
    cases: Vec<Case>,
    #[serde(default)]
    case_patterns: Vec<CasePattern>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    models: Vec<String>,
}

#[derive(Deserialize)]
struct CasePattern {
    glob: String,
    #[serde(default)]
    id_prefix: String,
    models: Vec<String>,
}

fn main() {
    let manifest_path =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir")).join("rom_tests.yaml");
    println!("cargo::rerun-if-changed={}", manifest_path.display());

    let manifest_source =
        fs::read_to_string(&manifest_path).expect("ROM test manifest should be readable");
    let manifest: Manifest =
        serde_saphyr::from_str(&manifest_source).expect("ROM test manifest should be valid YAML");
    let manifest_dir = manifest_path
        .parent()
        .expect("manifest should have a parent");
    let rom_root = manifest_dir.join(&manifest.rom_root);
    let cells = manifest
        .suites
        .into_iter()
        .flat_map(|mut suite| {
            let mut matched_paths = BTreeSet::new();
            for pattern in suite.case_patterns {
                let suite_dir = rom_root.join(&suite.name);
                let absolute_pattern = suite_dir.join(&pattern.glob);
                for path in glob::glob(&absolute_pattern.to_string_lossy())
                    .expect("ROM case glob should be valid")
                {
                    let path = path.expect("ROM case glob should be readable");
                    if !matched_paths.insert(path.clone()) {
                        continue;
                    }
                    let stem = path
                        .file_stem()
                        .and_then(|stem| stem.to_str())
                        .expect("ROM case path should have a UTF-8 file stem");
                    suite.cases.push(Case {
                        id: format!("{}{}", pattern.id_prefix, stem),
                        models: pattern.models.clone(),
                    });
                }
            }
            suite.cases
        })
        .flat_map(|case| {
            case.models
                .into_iter()
                .map(move |model| (case.id.clone(), model))
        })
        .collect::<Vec<_>>();
    assert!(
        !cells.is_empty(),
        "ROM test manifest must contain at least one matrix cell"
    );

    let mut generated = String::new();
    writeln!(
        generated,
        "// @generated by gbc/rom_test/build.rs - do not edit manually.\n\
         const GENERATED_ROM_CELL_COUNT: usize = {};",
        cells.len()
    )
    .unwrap();

    for (index, (case_id, model)) in cells.iter().enumerate() {
        writeln!(
            generated,
            "#[test]\nfn {}() {{\n    run_generated_manifest_cell({case_id:?}, {model:?});\n}}\n",
            test_name(index, case_id, model),
        )
        .unwrap();
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR should be available"));
    fs::write(out_dir.join("generated_rom_manifest_tests.rs"), generated)
        .expect("generated ROM tests should be written");
}

fn test_name(index: usize, case_id: &str, model: &str) -> String {
    let mut name = format!("rom_case_{index:04}_");
    for character in case_id.chars().chain(['_']).chain(model.chars()) {
        if character.is_ascii_alphanumeric() {
            name.push(character.to_ascii_lowercase());
        } else {
            name.push('_');
        }
    }
    name
}
