[package]
name = "nesgui"
version = "0.1.0"
authors = ["Mitsuharu Seki <mitsu1986@gmail.com>"]

[dependencies]
nes = {path = "../nes"}
glutin = "*"
gl = "*"
# glium = "*"
log = "*"
simple_logger = "*"
failure = { version = ">=0.0.0" }
