[package]
name = "nerust_gba_settings"
description = "GBA-specific settings types"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
dyn-clone.workspace = true
dyn-eq.workspace = true
nerust_core_traits.workspace = true
nerust_settings_traits.workspace = true
serde.workspace = true
strum.workspace = true
typetag.workspace = true
